plugins:
  - jekyll-relative-links
#  - jekyll-target-blank

relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-slate

title: "Ursinus WebIDE"
description: "Ursinus WebIDE"

url                      : https://BillJr99.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/Ursinus-WebIDE" # the subpath of your site, e.g. "/blog"

formlink: https://docs.google.com/forms/d/e/1FAIpQLSc3ZmIn4BbwUIfl5ernYZJb9-TFku14H7VT_Ex8rlKVc4yP7A/formResponse?submit=Submit&usp=pp_url&entry.1829751362=magic&entry.1803296527=
publickey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAquYU7gGa7s3d5SDXYHwcsKzbyU/P0GZjJp2ndTSjqhsSFVvpz39ITK1pMhAxWKBs1CqKfxq/x0QSbMmR1fErXAeYQbrNBI1M3R97Gh50u8aBEEQDLCs8iOxc940lLbPrDgVNms81IxnSub88vqRUgQ87/VXQsY6syhLGWVksfMQEeSvwTS0TsvDbbcltAoRAWcGcRBUr4iTr8DDhYOQpG5iKYNiwqCPlIPFWLcc80tW3ngggRLU1kKkybIV9znYM8BFj01YfkfHKkASm2LwY7XeXai0SuFm5iPwfcoqNhjWkVmvuNDFvoD19S9c2U/JaMwoisTvKUZjRiQYwUiXJ9wIDAQAB
    -----END PUBLIC KEY-----
    
# Reading Files
include:
  - .htaccess
  - _pages
  - files

assets:
  sources:
    - assets
